### ISSUE TITLE
Ask Your Questions

### ISSUE THREAD

**Issue by Seyitq** [Seyitq/nrf24l01-wifi-jammer#1]
Ask Your Questions please

**Comment by MassFrequencies** [comment]
\Documents\Arduino\libraries\Adafruit_SSD1306\Adafruit_SSD1306.cpp:42:10: fatal error: pgmspace.h: No such file or directory
 #include <pgmspace.h>
          ^~~~~~~~~~~~
compilation terminated.

Please help.

**Comment by Seyitq** [comment]
can you open an another issue
